language: go

go:
    - 1.12.x

install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs npm
    - npm install
    - go get -u github.com/gopherjs/gopherjs github.com/mattn/go-sqlite3 github.com/jmoiron/sqlx
    - go get -u -d -tags=js github.com/flimzy/go-sql.js
    # Syscall support
    - ( cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/;
        npm install --global node-gyp source-map-support;
        node-gyp rebuild;
        mkdir -p ~/.node_libraries/;
        cp build/Release/syscall.node ~/.node_libraries/syscall.node )

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - go test github.com/flimzy/anki
    - gopherjs test github.com/flimzy/anki
