language: go

go:
    - 1.10.x

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs npm
    - npm install

install:
    - go get -u github.com/gopherjs/gopherjs github.com/mattn/go-sqlite3 github.com/jmoiron/sqlx
    - go get -u -d -tags=js github.com/flimzy/go-sql.js
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
    # Syscall support
    - >
    ( cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/;
        npm install --global node-gyp;
        node-gyp rebuild;
        mkdir -p ~/.node_libraries/;
        cp build/Release/syscall.node ~/.node_libraries/syscall.node )

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - golangci-lint run ./...
    - go test -race github.com/flimzy/anki
    - gopherjs test github.com/flimzy/anki
